### ISSUE TITLE
cardano-cli only supports 64chars for the `--drep-metadata-url` parameter

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-cli#552] opened 2024-01-07 20:03 UTC
```console
$ cardano-cli version
cardano-cli 8.17.0.0 - linux-x86_64 - ghc-8.10
git rev a4a8119b59b1fbb9a69c79e1e6900e91292161e7
```
cardano-cli only allowes a max. length of 64char to be used with the
```
--drep-metadata-url TEXT DRep anchor URL
```
parameter. the parameter is part of the
```
cardano-cli conway governance drep registration-certificate
```
command.

according to the [conway.cddl](https://github.com/IntersectMBO/cardano-ledger/blob/a596eef045d19b7dcfbb410fca8362a65ec2258e/eras/conway/impl/cddl-files/conway.cddl#L373) it should be possible to have a 128char long URL now in conway-era.
```
url = tstr .size (0..128)
```

providing an URL text longer than 64chars, the cli crashes with an error:
```
cardano-cli: Url longer than 64 bytes
CallStack (from HasCallStack):
  error, called at src/Cardano/CLI/EraBased/Options/Common.hs:890:23 in cardano-cli-8.17.0.0-inplace:Cardano.CLI.EraBased.Options.CommonError: Failed all parsers
```

**Comment by smelc** [comment] 2024-03-21 14:32
@gitmachtl> can you provide an anchor URL that triggers the error?

I tried a few between 64 and 128 chars on the HEAD of https://github.com/IntersectMBO/cardano-cli/commits/smelc/fix-metadata-url-64-chars-limit/, but couldn't reproduce the failure. The call to `cardano-cli` succeeds :shrug:

**Comment by gitmachtl** [comment] 2024-03-21 15:13
i tried it again now with cli 8.20.3.0 and also couldn't reproduce the failure for the drep anchor url. so there must have been a fix after cli 8.17.0.0 😄 

do you know, can this 64char limitation now also be lifted for general content in metadata too?

**Comment by smelc** [comment] 2024-03-21 16:19
> do you know, can this 64char limitation now also be lifted for general content in metadata too

@gitmachtl> which command do you have in mind? [governance hash anchor-data](https://github.com/IntersectMBO/cardano-cli/blob/main/cardano-cli/test/cardano-cli-golden/files/golden/help.cli#L6483) for example?

**Comment by gitmachtl** [comment] 2024-03-21 17:07
I already tested the anchor with a vote, that works too.

I ment the general limitations we have when "attaching" metadata to a transaction in JSON format `--metadata-json-file` with strings included. https://developers.cardano.org/docs/transaction-metadata/#schema

**Comment by smelc** [comment] 2024-03-27 10:41
> I ment the general limitations we have when "attaching" metadata to a transaction in JSON format --metadata-json-file with strings included. developers.cardano.org/docs/transaction-metadata/#schema

This should be discussed with someone else than me, since it's a high-level restriction on which I have no influence :rofl:

So I'm closing this issue as its original point is solved.

**Closed as completed by smelc** 2024-03-27 10:41 UTC
